# Autogenerated from /Volumes/workplace/packet-mlir/tests/lit.cmake.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
import os
import platform
def path(p):
    if not p: return ''
    # Follows lit.util.abs_path_preserve_drive, which cannot be imported here.
    if platform.system() == 'Windows':
        return os.path.abspath(os.path.join(os.path.dirname(__file__), p))
    else:
        return os.path.realpath(os.path.join(os.path.dirname(__file__), p))


config.llvm_tools_dir = lit_config.substitute("/Volumes/workplace/packet-mlir/external/llvm-project/build/./bin")
config.mlir_obj_dir = "/Volumes/workplace/packet-mlir/build"
config.llvm_shlib_ext = ""
config.project_binary_dir = "/Volumes/workplace/packet-mlir/build"
config.project_source_dir = "/Volumes/workplace/packet-mlir"

import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work.
lit_config.load_config(config, "/Volumes/workplace/packet-mlir/tests/lit.cmake.cfg.py")
